use_frameworks!

target 'TeleportiOS_Example' do
  pod 'TeleportiOS', :path => '../'

  target 'TeleportiOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
